apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-rp3o
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-rp3o
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-rp3o
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-rp3o
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-rp3o
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dwmq-tenant/rhtap-demo-app/hacbs-test-project-rp3o@sha256:2003b23e758d376c07facd91863e08d895c8590b58ea63f5302bad881fdec0b3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
